-- VIEW ALL DATA FROM THE STUDENTS TABLE
SELECT * FROM students;

-- VIEW ALL DATA FROM THE COURSES TABLE
SELECT * FROM courses;

-- VIEW ALL DATA FROM THE ENROLLMENTS TABLE
SELECT * FROM enrollments;