-- SELECT ALL DATA FROM THE TABLE
SELECT * FROM lpu_students;

-- SELECT SPECIFIC DATA FROM THE TABLE
SELECT first_name, last_name, cgpa FROM lpu_students;

-- SELECT DATA FROM THE TABLE WITH A CONDITION
SELECT * FROM lpu_students WHERE cgpa >= 8.5;

-- SELECT DATA FROM THE TABLE WITH MULTIPLE CONDITIONS
SELECT * FROM lpu_students WHERE cgpa >= 8.5 AND is_placed = TRUE;

-- SELECT DATA FROM THE TABLE WITH OR CONDITION
SELECT * FROM lpu_students WHERE cgpa >= 8.5 OR is_placed = TRUE;

-- SELECT DATA FROM THE TABLE WITH ORDER BY
SELECT * FROM lpu_students ORDER BY cgpa DESC;

-- SELECT DATA FROM THE TABLE WITH ORDER BY AND LIMIT
SELECT * FROM lpu_students ORDER BY cgpa DESC LIMIT 5;

-- SELECT DATA FROM THE TABLE WITH ORDER BY AND LIMIT AND OFFSET
SELECT * FROM lpu_students ORDER BY cgpa DESC LIMIT 5 OFFSET 5;

-- SELECT DATA FROM THE TABLE WITH WHERE, ORDER BY, LIMIT, AND OFFSET
SELECT * FROM lpu_students WHERE is_placed = TRUE ORDER BY cgpa DESC LIMIT 5 OFFSET 1;

-- SELECT DATA FROM THE TABLE WITH WHERE, GROUP BY, HAVING, ORDER BY, LIMIT, AND OFFSET
SELECT branch, AVG(cgpa) FROM lpu_students WHERE is_placed = TRUE GROUP BY branch HAVING AVG(cgpa) >= 8.5 ORDER BY AVG(cgpa) DESC LIMIT 5 OFFSET 1;

