-- SELECT ALL DATA FROM THE TABLE
SELECT * FROM students;

-- SELECT SPECIFIC COLUMNS (STUDENT NAME AND CGPA) FROM THE TABLE
SELECT student_name, cgpa FROM students;

-- SELECT DATA WITH A SINGLE WHERE CONDITION (CGPA >= 8.5)
SELECT * FROM students WHERE cgpa >= 8.5;

-- SELECT DATA WITH MULTIPLE CONDITIONS (AND LOGIC)
SELECT * FROM students WHERE cgpa >= 8.5 AND is_placed = TRUE;

-- SELECT DATA WITH OR CONDITION
SELECT * FROM students WHERE cgpa >= 8.5 OR is_placed = TRUE;

-- SELECT DATA SORTED BY CGPA IN DESCENDING ORDER (HIGHEST TO LOWEST)
SELECT * FROM students ORDER BY cgpa DESC;

-- SELECT DATA SORTED BY CGPA IN DESCENDING ORDER WITH LIMIT (TOP 5 STUDENTS)
SELECT * FROM students ORDER BY cgpa DESC LIMIT 5;

-- SELECT DATA SORTED BY CGPA IN DESCENDING ORDER WITH LIMIT AND OFFSET (PAGINATION: ROWS 6 TO 10)
SELECT * FROM students ORDER BY cgpa DESC LIMIT 5 OFFSET 5;

-- SELECT DATA FILTERED, SORTED, WITH LIMIT AND OFFSET
SELECT * FROM students WHERE is_placed = TRUE ORDER BY cgpa DESC LIMIT 5 OFFSET 1;

-- SELECT DATA WITH WHERE, GROUP BY, HAVING, ORDER BY, LIMIT, AND OFFSET (COMPLEX QUERY)
SELECT branch, AVG(cgpa) FROM students WHERE is_placed = TRUE GROUP BY branch HAVING AVG(cgpa) >= 8.5 ORDER BY AVG(cgpa) DESC LIMIT 5 OFFSET 1;

