-- ADVANCED FILTERING: SELECT STUDENTS WHERE AGE IS NULL
SELECT student_id, student_name FROM students WHERE age IS NULL;

-- NOTE: Using '=' with NULL (age = NULL) will NOT return any rows.
-- In SQL, you must always use 'IS NULL' to find NULL values.
SELECT student_id, student_name FROM students WHERE age = NULL;

-- SELECT STUDENTS BETWEEN AGE 18 AND 21
SELECT * FROM students WHERE age BETWEEN 18 AND 21;

-- SELECT STUDENTS FROM SPECIFIC CITIES (HOUSTON, LOS ANGELES, CHICAGO)
SELECT * FROM students WHERE city IN ('Houston', 'Los Angeles', 'Chicago');

-- SELECT STUDENTS IN SPECIFIC BRANCHES (ELECTRICAL OR MECHANICAL ENGINEERING)
SELECT * FROM students WHERE branch IN ('Electrical Engineering', 'Mechanical Engineering');

-- SELECT STUDENTS WITH SPECIFIC IDs (REPLACED REG_ID WITH STUDENT_ID)
SELECT * FROM students WHERE student_id IN (1, 4, 9);

-- SELECT STUDENTS WHOSE NAME STARTS WITH 'R'
SELECT * FROM students WHERE student_name LIKE 'R%';

-- SELECT STUDENTS WHOSE NAME ENDS WITH 'n'
SELECT * FROM students WHERE student_name LIKE '%n';

-- SELECT STUDENTS WHOSE NAME CONTAINS 'ra'
SELECT * FROM students WHERE student_name LIKE '%ra%';

-- SELECT STUDENTS WHERE CITY STARTS WITH 'D'
SELECT * FROM students WHERE city LIKE 'D%';

-- SELECT STUDENTS WHERE BRANCH ENDS WITH 'e'
SELECT * FROM students WHERE branch LIKE '%e';

-- SELECT STUDENTS WHOSE FULL NAME IS EXACTLY 4 CHARACTERS
SELECT * FROM students WHERE student_name LIKE '____';

-- SORT STUDENTS BY NAME IN ASCENDING ORDER
SELECT * FROM students ORDER BY student_name;

-- SORT STUDENTS BY CITY IN ASCENDING ORDER
SELECT * FROM students ORDER BY city;

-- SORT STUDENTS BY CGPA FROM HIGHEST TO LOWEST (DESCENDING)
SELECT * FROM students ORDER BY cgpa DESC;

-- SORT STUDENTS BY branch THEN BY student_name
SELECT * FROM students ORDER BY branch, student_name;

-- SORT STUDENTS BY AGE FROM YOUNGEST TO OLDEST (ASCENDING)
SELECT * FROM students ORDER BY age ASC;